library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(rhandsontable)
library(data.table)
library(plotly)
library(taRifx)
library(reshape)
library(DT)


source('./ui_controls.R')
source('./server.R')
source('./Functions/calcCurrentScore.R')
source('./Functions/readResults.R')
